project:
  outputs_dir: results
  # waypoints_dir: waypoints
  waypoints_dir: aaaaaaaaa

simulation:
  seed: 32
  number_runs: 1
  scenario: fixed # fixed | random | excel

grid:
  # spacing: 92.608
  spacing: 60

  # Used only when scenario = random or excel
  width: 3
  height: 3

depot:
  location: [0, 0]

uav:
  # speed: 16
  # max_flight_time: 1920
  speed: 1
  max_flight_time: 600

  # Used only when scenario = fixed or random
  num_uavs: 2

waypoints:
  # Used only when scenario = random
  number_targets: 6

  # Used only when scenario = random or excel
  base_revenue: 30
  min_revenue: 60
  max_revenue: 600

  # Used only when scenario = fixed
  revenue_matrix: 
    - [0, 1, 0]
    - [6, 0, 10]
    - [2, 11, 6]
